default:
  image:
    name: "registry.access.redhat.com/ubi9/ubi-minimal"
    entrypoint: [""]

stages:
  - sync

run-sync:
  rules:
    # only run on main branch, when secret exists and pipeline is triggered by schedule
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && "$SYNC_TOKEN" && $CI_PIPELINE_SOURCE == "schedule"
    # Let the pipeline run for our testing branch
    # - if: $CI_COMMIT_BRANCH == "ubi-minimal"
  stage: sync
  tags: [shared-podman]
  before_script:
    - TXT_RED="\e[31m" && TXT_CLEAR="\e[0m"
    - echo -e "Sync server prep ${TXT_RED}started${TXT_CLEAR} at `date` by $CI_PIPELINE_SOURCE"
    # Install RH certs using the prepared script in the image
    - curl https://certs.corp.redhat.com/certs/2015-IT-Root-CA.pem > /etc/pki/ca-trust/source/anchors/RH-IT-Root-CA.crt
    - curl https://certs.corp.redhat.com/certs/2022-IT-Root-CA.pem > /etc/pki/ca-trust/source/anchors/2022-IT-Root-CA.pem
    - update-ca-trust

    # install git and dependencies
    - echo "Sync server dependencies started at `date` by $CI_PIPELINE_SOURCE"
    - microdnf install python3-pip git findutils -y
    - git config --global user.email "mramendi@redhat.com"
    - git config --global user.name "sync bot"
    - git config --global push.autoSetupRemote true
    - pip3 install pyyaml aura.tar.gz

  script:
    - echo "sync server started at `date` by $CI_PIPELINE_SOURCE"
    # clone repos
    - sh setup-repos.sh "$SYNC_TOKEN"

    - echo "Repo cloning completed at `date`"

    # process sync.yaml to create sync.sh
    - python3 yaml-to-sh.py

    # Run sync.sh, which runs the sync server for all branches
    - sh sync.sh

    - echo "Sync server completed at `date`"
